name: UnprecendentedCustomizer
version: '${project.version}'
main: com.scoddle.unprecendentedcustomizer.UnprecendentedCustomizer
api-version: 1.16
commands:
  "test":
    description: Test cmd lul
  admin:
    description: Admin Command